// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solution.Core.Conext;

#nullable disable

namespace Solution.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Solution.Core.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Club")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = "1992.05.03",
                            Club = "FATUM Nyíregyháza",
                            Description = "Nikola Radosová (born 3 May 1992) is a Slovak female volleyball player. She is part of the Slovakia women's national volleyball team. She competed at the 2019 Women's European Volleyball Championship.",
                            Height = 1.8600000000000001,
                            ImageLink = "https://t.aimg.sk/magaziny/jQg6qSKSS-6QkmTfMGAKDg~Volejbalistka-Nikola-Radosov.jpg?t=LzB4ODU6MTA2N3g2ODUvZml0LWluLzE2MDB4OTAw&h=Wga6PqMq3hI4_zELe2x9rA&e=2145916800&v=3",
                            Name = "Nikola Radosová",
                            PositionId = 4,
                            Weight = 66
                        },
                        new
                        {
                            Id = 2,
                            Birthday = "1983.03.21",
                            Club = "1. MCM-Diamant",
                            Description = "Tanja Matic több száz szerb élvonalbeli mérkőzéssel a háta mögött, a patinás Szpartak Szabadka korábbi csapatkapitányaként 2015 nyarán érkezett hazánkba, és előbb két éven át játszott Békéscsabán, majd két szezont húzott le Nyíregyházán. A csabaiakkal mindent megnyert, amit csak itthon lehetett: a bajnokságban és a Magyar Kupában is két-két elsőséggel gazdagodott, emellett egy Közép-európai Liga elsőséget is begyűjtött. A nyíregyháziakkal két alkalommal hódította el a Magyar Kupa-trófeát, és 2018-ban, illetve 2019-ben is bejutott a bajnokság döntőjébe, ahol végül ezüstéremmel zárt. A tapasztalt röplabdázó ezek után, pályafutásának újabb állomásaként Kaposvárt választotta, így újra együtt dolgozhatott korábbi edzőjével, Sasa Nedeljkoviccsal. A 2019/2020-as évadban elért eredményekre mindenki büszke lehet, de mivel az ismert okok miatt váratlanul félbeszakadt, majd véget is ért a pontvadászat, mindenki kettőzött erővel szeretne majd újra munkába állni",
                            Height = 179.0,
                            ImageLink = "https://1mcmvolley.hu/wp-content/uploads/2020/09//2019.10.24-2.jpg",
                            Name = "Tanja Matic",
                            PositionId = 4,
                            Weight = 57
                        },
                        new
                        {
                            Id = 3,
                            Birthday = "1983.06.30",
                            Club = "Barueri",
                            Description = "Katarzyna Ewa Skowrońska-Dolata egykori lengyel röplabdázó, a lengyel női röplabda-válogatott és az olasz Foppapedretti Bergamo klub tagja, kettős Európa-bajnok, olasz, török, kínai és azeri nemzeti bajnokság aranyérmese.",
                            Height = 188.0,
                            ImageLink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBrypz5TGmd6zLI19niR_UwuO_uYOKmBbRxg&usqp=CAU",
                            Name = "Katarzyna Skowrońska-Dolata",
                            PositionId = 4,
                            Weight = 75
                        },
                        new
                        {
                            Id = 4,
                            Birthday = "1984.05.14",
                            Club = "KPS Chemik Police",
                            Description = "Anna Werblińska lengyel röplabdázó, a lengyel női röplabda-válogatott tagja 2006–2016-ban, a Pekingi Olimpiai Játékok résztvevője, a 2009-es Európa-bajnokság bronzérmese és négyszeres lengyel bajnok.",
                            Height = 1.78,
                            ImageLink = "https://upload.wikimedia.org/wikipedia/commons/6/68/Anna_Werbli%C5%84ska_%2812194794495%29.jpg",
                            Name = "Anna Werblińska",
                            PositionId = 4,
                            Weight = 69
                        },
                        new
                        {
                            Id = 5,
                            Birthday = "1986.02.20",
                            Club = "KPS Chemik Police",
                            Description = "Agnieszka Bednarek-Kasza lengyel röplabdázó, a lengyel női röplabda-válogatott és a lengyel KPS Chemik Police klub tagja, a Peking 2008 olimpiai játékok résztvevője, a 2009-es Európa-bajnokság bronzérmese, Lengyel bajnok.",
                            Height = 1.8500000000000001,
                            ImageLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bednarek-Pekin_2008.jpg/800px-Bednarek-Pekin_2008.jpg",
                            Name = "Agnieszka Bednarek-Kasza",
                            PositionId = 2,
                            Weight = 69
                        },
                        new
                        {
                            Id = 6,
                            Birthday = "1978.10.25",
                            Club = "MKS Dąbrowa Górnicza",
                            Description = "Eleonora Dziękiewicz lengyel röplabdázó, a lengyel női röplabda-válogatott és a lengyel Tauron MKS Dąbrowa Górnicza klub tagja, a 2009-es Európa-bajnokság bronzérmese, háromszoros lengyel bajnok",
                            Height = 1.8500000000000001,
                            ImageLink = "https://dl.siatkarskaliga.pl/68831/inline/scalecrop=400x800/9c119d/Eleonora-Dziekiewicz.jpg",
                            Name = "Eleonora Dziękiewicz",
                            PositionId = 2,
                            Weight = 78
                        },
                        new
                        {
                            Id = 7,
                            Birthday = "1979.01.10",
                            Club = "Futura Volley Busto Arsizio",
                            Description = "Francesca Piccinini olasz röplabdázó, aki négyszer képviselte Olaszországot a nyári olimpián. Tagja volt a női válogatottnak, amely aranyérmet nyert a 2002-es németországi világbajnokságon. 1995. június 10-én debütált Olaszországban az Egyesült Államok ellen.",
                            Height = 1.8400000000000001,
                            ImageLink = "https://i.ytimg.com/vi/LjRmWzwz-nk/hqdefault.jpg",
                            Name = "Francesca Piccinini",
                            PositionId = 4,
                            Weight = 62
                        },
                        new
                        {
                            Id = 8,
                            Birthday = "1983.12.31",
                            Club = "Osasco Audax",
                            Description = "Jaqueline Maria Pereira de Carvalho Endres brazil röplabdázó, a brazil csapat tagja, amely megnyerte az olimpiai játékokat Pekingben 2008 és London 2012-ben",
                            Height = 1.8600000000000001,
                            ImageLink = "https://alchetron.com/cdn/jaqueline-carvalho-12811a8c-5f68-4099-8345-7d8a58f65dd-resize-750.jpeg",
                            Name = "Jaqueline Carvalho",
                            PositionId = 4,
                            Weight = 70
                        },
                        new
                        {
                            Id = 9,
                            Birthday = "1995.03.03",
                            Club = "Leningradka Saint-Petersburg",
                            Description = "Yelyzaveta Samadova-Ruban ukrán születésű azerbajdzsáni röplabdázó, aki jelenleg az olasz Pallavolo Scandicci és az azerbajdzsáni női röplabda-válogatottban játszik külső spikerként.",
                            Height = 1.8500000000000001,
                            ImageLink = "https://s21466.pcdn.co/wp-content/uploads/2018/10/YelyzavetaSamadovaofAzerbaijanspikesthebal-e1539604875126.jpg",
                            Name = "Yelyzaveta Samadova",
                            PositionId = 4,
                            Weight = 71
                        },
                        new
                        {
                            Id = 10,
                            Birthday = "1987.06.22",
                            Club = "Beshiktas",
                            Description = "Eda Erdem Dündar török ​​röplabdázó. 190 cm magas, és középső blokkolóként játszik. Erdem tömbmagassága 302 cm, tüske magassága 308 cm. Jelenleg a Fenerbahçe SK csapatában játszik, és mind a klub, mind a török ​​röplabda -válogatott kapitánya",
                            Height = 1.8799999999999999,
                            ImageLink = "https://i.ytimg.com/vi/EU3075haQeA/maxresdefault.jpg",
                            Name = "Eda Erdem Dündar",
                            PositionId = 5,
                            Weight = 73
                        },
                        new
                        {
                            Id = 11,
                            Birthday = "1998.02.19.",
                            Club = "UCLA",
                            Description = "Jamie Robbins is one of the most beautiful volleyball players. She plays on the UCLA volleyball team. Her position is an outside hitter. Although we can’t consider her as a professional volleyball player, she is pretty popular with over 120k Instagram followers. ",
                            Height = 1.8500000000000001,
                            ImageLink = "https://i1.wp.com/tstreetvolleyball.com/wp-content/uploads/2019/05/web-18-Shawn-Robbins-Jaime-8-HL5A8412-118-250x350.jpg?fit=250%2C350&ssl=1",
                            Name = "Jamie Robbins",
                            PositionId = 4,
                            Weight = 61
                        },
                        new
                        {
                            Id = 12,
                            Birthday = "1999.07.07",
                            Club = "Vakıfbank Istanbul",
                            Description = "Zehra Güneş török ​​röplabdázó. 1,97 m magas, 88 kg, középső blokkoló pozícióban játszik. Jelenleg a Vakıfbank Istanbul csapatában játszik, és a török ​​női röplabda-válogatott tagja.",
                            Height = 1.97,
                            ImageLink = "https://s.yimg.com/ny/api/res/1.2/rzzeYSjj.dK9f9Sj_JHBnQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTIwMDA7aD0xMzMz/https://s.yimg.com/os/creatr-uploaded-images/2021-08/beb34af0-f434-11eb-bd5d-8a19df83047c",
                            Name = "Zehra Güneş",
                            PositionId = 2,
                            Weight = 88
                        },
                        new
                        {
                            Id = 13,
                            Birthday = "1998.03.30",
                            Club = "HAOK Mladost Zagreb",
                            Description = "Klara Perić horvát röplabdázó. Szetterként játszik a horvát HAOK Mladost klubban.",
                            Height = 1.8500000000000001,
                            ImageLink = "https://cdn.nwmgroups.hu/s/img/i/2201//20220105klara-peric-roplabda.jpg",
                            Name = "Klara Perić",
                            PositionId = 4,
                            Weight = 71
                        },
                        new
                        {
                            Id = 14,
                            Birthday = "1998.11.25",
                            Club = "Grot Budowlani Łódź",
                            Description = "Maria Stenzel lengyel röplabdázó. A lengyel női röplabda -válogatott tagja. Részt vett a 2015 -ös FIVB röplabda lányok U18 -as világbajnokságán, a 2017 -es FIVB röplabda női U20 -as világbajnokságon és a 2018 -as FIVB röplabda Női Nemzetek Ligájában. Klubszinten a Grot Budowlani Łódź csapatában játszott.",
                            Height = 167.0,
                            ImageLink = "https://ocdn.eu/pulscms-transforms/1/yqXk9kqTURBXy8yYWQxYWVjMzQ2MWQ5OTkxZjE3YmNmMjFhMjFlYjhkMC5qcGVnk5UDAcyBzQu3zQaWkwmmZTk5N2EyBpMFzQSwzQJ2gaEwAQ/maria-stenzel.jpg",
                            Name = "Maria Stenzel",
                            PositionId = 4,
                            Weight = 63
                        },
                        new
                        {
                            Id = 15,
                            Birthday = "1987.07.30",
                            Club = "Olympiakos CFP",
                            Description = "Mariana Andrade Costa, más néven Mari Paraíba brazil női röplabdázó. A brazíliai női röplabda-válogatott tagja. Klubszinten az Osasco Voleibol Clube, az EC Pinheiros és a Minas Tênis Clube csapatában játszott. Jelenleg az Olympiakos CFP-nél játszik",
                            Height = 1.8100000000000001,
                            ImageLink = "https://i.redd.it/smql3twwyxf61.jpg",
                            Name = "Mariana Costa",
                            PositionId = 3,
                            Weight = 75
                        },
                        new
                        {
                            Id = 16,
                            Birthday = "1994.11.22",
                            Club = "Fenerbahçe",
                            Description = "Mariana Andrade Costa, más néven Mari Paraíba brazil női röplabdázó. A brazíliai női röplabda-válogatott tagja. Klubszinten az Osasco Voleibol Clube, az EC Pinheiros és a Minas Tênis Clube csapatában játszott. Jelenleg az Olympiakos CFP-nél játszik",
                            Height = 1.8799999999999999,
                            ImageLink = "https://www.ilawjournals.com/wp-content/uploads/2021/07/Samantha-Bricio.jpg",
                            Name = "Samantha Bricio",
                            PositionId = 5,
                            Weight = 58
                        },
                        new
                        {
                            Id = 17,
                            Birthday = "1995.01.06",
                            Club = "Telekom Baku",
                            Description = "Winifer María Fernández Pérez (born 6 January 1995) is a Dominican female volleyball player. With her club Mirador she competed at the 2015 FIVB Club World Championship. She became well known after a video and later some photos of her playing and training, and personal photos of her--some of them fake--went viral in July 2016. ",
                            Height = 1.6899999999999999,
                            ImageLink = "https://www.ilawjournals.com/wp-content/uploads/2021/07/Samantha-Bricio.jpg",
                            Name = "Winifer Fernández",
                            PositionId = 2,
                            Weight = 62
                        },
                        new
                        {
                            Id = 18,
                            Birthday = "1989.06.01",
                            Club = "ROC",
                            Description = "Nataliya Olegovna Goncharova, 2012 és 2016 között Obmochaeva, orosz női röplabdázó. 2010 -ig az ukrán női röplabda -válogatottban játszott, amikor az orosz női röplabda -válogatott tagja lett.",
                            Height = 1.8899999999999999,
                            ImageLink = "https://worldofvolley.com/wp-content/uploads/2021/05/unnamed-file-12921.jpg",
                            Name = "Nataliya Goncharova",
                            PositionId = 4,
                            Weight = 75
                        },
                        new
                        {
                            Id = 19,
                            Birthday = "1994.09.23",
                            Club = "Lokomotiv Kaliningrad",
                            Description = "Louisa-Christin Lippmann német női röplabdázó. Külső ütőként vagy ellentétesen játszik, és több mint 100 alkalommal szerepel a német női röplabda-válogatottban. Klubszinten jelenleg a Kalinyingrádi Lokomotiv csapatában játszik.",
                            Height = 1.9099999999999999,
                            ImageLink = "https://i.pinimg.com/736x/5c/2a/29/5c2a2996ce6e78d5d97245411c15caef.jpg",
                            Name = "Louisa Lippmann",
                            PositionId = 4,
                            Weight = 74
                        },
                        new
                        {
                            Id = 20,
                            Birthday = "1995.08.13",
                            Club = "Bayamón",
                            Description = "Vilmarie Mojica Puerto Rico-i röplabdázó, aki a női válogatott csapatkapitánya volt a 2008-as japán olimpiai kvalifikációs tornán. Ott a csapat a nyolcadik és az utolsó helyen végzett, miután vadkártyát kapott az eseményre, miután Peru és Kenya visszalépett.",
                            Height = 1.8,
                            ImageLink = "https://volleybox.net/media/upload/players/1430051555SFXh6.jpg",
                            Name = "Vilmarie Mojica",
                            PositionId = 1,
                            Weight = 63
                        });
                });

            modelBuilder.Entity("Solution.Core.Models.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spiker"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Setter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Libero"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Opposite"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Center"
                        });
                });

            modelBuilder.Entity("Solution.Core.Models.Entities.Player", b =>
                {
                    b.HasOne("Solution.Core.Models.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
